apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo-jx.n8m.nl/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: nigle-dev
    repository: jx3-kubernetes
  - key: staging
  - key: production
  ingress:
    domain: n8m.nl
    externalDNS: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: "nils@glerum.eu"
      enabled: false
      production: false
  pipelineUser:
    username: nigle-dev
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
