apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: https://bucketrepo-jx.n8m.nl/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: nigle-dev
    repository: jx3-kubernetes
  - key: staging
  - key: production
  ingress:
    annotations:
      cert-manager.io/issuer: letsencrypt-production
      cert-manager.io/issuer-kind: ClusterIssuer
    domain: n8m.nl
    externalDNS: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: nils@glerum.eu
      enabled: true
      production: false
    annotations:
      cert-manager.io/issuer: letsencrypt-production
      cert-manager.io/issuer-kind: ClusterIssuer
      kubernetes.io/ingress.class: "nginx"
  pipelineUser:
    username: nigle-dev
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
