filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo-jx.n8m.nl/bucketrepo/charts/
releases:
- chart: dev/py-http
  version: 0.0.2
  name: py-http
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
