filepath: ""
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo-jx.n8m.nl/bucketrepo/charts/
releases:
- chart: dev/python-http2
  version: 0.0.1
  name: python-http2
templates: {}
renderedvalues: {}
