filepath: ""
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo-jx.n8m.nl/bucketrepo/charts/
releases:
- chart: dev/py-http
  version: 0.0.1
  name: py-http
templates: {}
renderedvalues: {}
