filepath: ""
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo-jx.n8m.nl
releases:
- chart: dev/golang-http
  version: 0.0.1
  name: golang-http
templates: {}
renderedvalues: {}
