apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        nigle-dev/golang-http: true
        nigle-dev/jx3-kubernetes: true
        nigle-dev/python-http: true
        nigle-dev/python-http2: true
        nigle-dev/python-http3: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        nigle-dev/golang-http: merge
        nigle-dev/jx3-kubernetes: merge
        nigle-dev/python-http: merge
        nigle-dev/python-http2: merge
        nigle-dev/python-http3: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - nigle-dev/jx3-kubernetes
        - nigle-dev/golang-http
        - nigle-dev/python-http
        - nigle-dev/python-http2
        - nigle-dev/python-http3
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - nigle-dev/jx3-kubernetes
        - nigle-dev/golang-http
        - nigle-dev/python-http
        - nigle-dev/python-http2
        - nigle-dev/python-http3
      target_url: http://lighthouse-jx.n8m.nl/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
